CREATE DATABASE Exercise1;
CREATE TABLE EMP_1(EMP_NUM CHAR(3), EMP_Lname VARCHAR(15), EMP_FNAME CHAR(15), EMP_INITIAL CHAR(1), EMP_HIREDATE DATE, JOB_CODE CHAR(3));
INSERT INTO EMP_1(EMP_NUM,EMP_Lname,EMP_FNAME,EMP_INITIAL,EMP_HIREDATE,JOB_CODE) VALUES('1','Donato','Denzel','K','2023-03-23','502');
INSERT INTO EMP_1(EMP_NUM,EMP_Lname,EMP_FNAME,EMP_INITIAL,EMP_HIREDATE,JOB_CODE) VALUES('2','Santos','Roy','F','2021-08-07','503');
INSERT INTO EMP_1(EMP_NUM,EMP_Lname,EMP_FNAME,EMP_INITIAL,EMP_HIREDATE,JOB_CODE) VALUES('3','Trek','Star','H','2020-09-04','504');
SELECT * FROM emp_1;